### ISSUE TITLE
强，谢谢大佬分享，这个是默认刷英雄篇吗

### ISSUE THREAD

**Issue by 1216332750** [deximy/FxxkSsxx#1]
这个是默认刷英雄篇吗

**Comment by deximy** [comment]
Yes

**Comment by 3195200013** [comment]
大佬有现成的exe吗，我的电脑里没有py软件，下载了py也不会用，py转exe太难了，我的电脑的命令提示符说没有pip这个命令

**Comment by 3195200013** [comment]
大佬有现成的exe文件吗，我不会转

**Comment by 1216332750** [comment]
用python直接运行就好了

**Comment by 3195200013** [comment]
i do not know

**Comment by 3195200013** [comment]
py看不懂，下载了

**Comment by 3195200013** [comment]
点软件需要点好几次，暴力点，然后输入了激活码之后秒退

**Comment by deximy** [comment]
> 大佬有现成的exe文件吗，我不会转

FxxkSsxx.exe不需要python环境应该也可以运行，直接去Release里面下载

**Comment by deximy** [comment]
> 点软件需要点好几次，暴力点，然后输入了激活码之后秒退

如果输完token之后程序自己退出的话应该就是token有误。

**Comment by 3195200013** [comment]
release是什么

**Comment by deximy** [comment]
> release是什么

https://github.com/deximy/FxxkSsxx/releases
