### ISSUE TITLE
错误代码： {'code': 4823, 'msg': 'Verification code failed.', 'status_code': 200} 完成考试时出错，

### ISSUE THREAD

**Issue by Promiss** [deximy/FxxkSsxx#12]
完成考试时出错，错误代码： {'code': 4823, 'msg': 'Verification code failed.', 'status_code': 200}
完成考试时出错，错误代码： {'code': 4823, 'msg': 'Verification code failed.', 'status_code': 200}
大佬错误代码了

**Comment by deximy** [comment]
Should be fixed in Release 1.3 .
