### ISSUE TITLE
小白回馈——更新后仍然报错误代码

### ISSUE THREAD

**Issue by wang281** [deximy/FxxkSsxx#16]
![2021-02-05 (2)](https://user-images.githubusercontent.com/78578297/107032798-57093d00-67ef-11eb-80f2-db53d685e7a9.png)

**Comment by deximy** [comment]
![image](https://user-images.githubusercontent.com/30504323/107106484-db4ad700-6866-11eb-87f9-f750508ee112.png)
暂时无法复现。需要进一步信息。

**Comment by SCX123SCX** [comment]
Traceback (most recent call last):
  File "E:\pytnon\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "E:\pytnon\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "E:\pytnon\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ssxx.univs.cn', port=443): Max retries exceeded with url: /cgi-bin/race/question/?activity_id=5f71e934bcdbf3a8c3ba5061&question_id=5571ef2e5d6fe02504ba58bf&mode_id=5f71e934bcdbf3a8c3ba51d6&way=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CD2C65A710>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by wang281** [comment]
![2021-02-06](https://user-images.githubusercontent.com/78578297/107106953-44cbe500-6869-11eb-8dbb-a87eb51a5edf.png)
![2021-02-06 (3)](https://user-images.githubusercontent.com/78578297/107106958-48f80280-6869-11eb-8e10-9b33fbe62a8e.png)
![2021-02-06 (2)](https://user-images.githubusercontent.com/78578297/107106961-4b5a5c80-6869-11eb-8ca3-ad4ad00e2172.png)
![2021-02-06 (1)](https://user-images.githubusercontent.com/78578297/107106963-4e554d00-6869-11eb-84f9-4cb5f1fb19bd.png)
现在是这个情况，请多多职教~

**Comment by deximy** [comment]
> ![2021-02-06](https://user-images.githubusercontent.com/78578297/107106953-44cbe500-6869-11eb-8dbb-a87eb51a5edf.png)
> ![2021-02-06 (3)](https://user-images.githubusercontent.com/78578297/107106958-48f80280-6869-11eb-8e10-9b33fbe62a8e.png)
> ![2021-02-06 (2)](https://user-images.githubusercontent.com/78578297/107106961-4b5a5c80-6869-11eb-8ca3-ad4ad00e2172.png)
> ![2021-02-06 (1)](https://user-images.githubusercontent.com/78578297/107106963-4e554d00-6869-11eb-84f9-4cb5f1fb19bd.png)
> 现在是这个情况，请多多职教~

不是最新版本，最新版本是1.3

**Comment by deximy** [comment]
> Traceback (most recent call last):
> File "E:\pytnon\lib\site-packages\requests\adapters.py", line 449, in send
> timeout=timeout
> File "E:\pytnon\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
> method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
> File "E:\pytnon\lib\site-packages\urllib3\util\retry.py", line 573, in increment
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ssxx.univs.cn', port=443): Max retries exceeded with url: /cgi-bin/race/question/?activity_id=5f71e934bcdbf3a8c3ba5061&question_id=5571ef2e5d6fe02504ba58bf&mode_id=5f71e934bcdbf3a8c3ba51d6&way=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001CD2C65A710>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

连接超时，检查自己的网络，如果是随缘出现（不定时出现）就当无事发生再重新打开软件接着跑就行了，如果不是非常频繁的话没必要处理

**Comment by wang281** [comment]
&nbsp;了解了 实在麻烦了 万分感谢亲~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "deximy"<notifications@github.com&gt;; 
发送时间: 2021年2月6日(星期六) 中午11:03
收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 
抄送: "Ⱥ~"<931619886@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [deximy/FxxkSsxx] 小白回馈——更新后仍然报错误代码 (#16)





  

 
 
 
 现在是这个情况，请多多职教~
  
不是最新版本，最新版本是1.3
