### ISSUE TITLE
Is there any necessity to use database?

### ISSUE THREAD

**Issue by deximy** [deximy/FxxkSsxx#17]
Due to more modes are supported in Release 1.3, there will be more and more items in _answer.txt_. Is there any need to use database like sqlite3 for more readable code and faster speed?

**Comment by chettoy** [comment]
I have considered using sqlite, but I am not familiar with python, and there is no problem with the current amount of questions stored in memory, answer.txt is only used for persistent storage and will not affect performance. However, If I have time later, I will try to do it.
If we use sqlite to storage, we can also store the text of the question and answer, and save the question bank after the event. The content stored now has no value after the event ends.
In addition, I am worried about someone using this code to make money.
I am learning C++, I may try to write a C++ version.

**Comment by deximy** [comment]
> I have considered using sqlite, but I am not familiar with python, and there is no problem with the current amount of questions stored in memory, answer.txt is only used for persistent storage and will not affect performance. However, If I have time later, I will try to do it.

Using sqlite will have better performance in loading compared with using _answer.txt_. Of course, memory has the best performance, so I will keep key-value structure as well as current version. I will finish it myself as there is nothing difficult.

> If we use sqlite to storage, we can also store the text of the question and answer, and save the question bank after the event. The content stored now has no value after the event ends.

Of course we can, but what's the meaning of keeping the content of title? I think MD5 is reliable enough.

> In addition, I am worried about someone using this code to make money.

We have nothing to do with this. Can not stop it.

> I am learning C++, I may try to write a C++ version.

No need to use C++ unless you want to challenge youself, LOL.

**Comment by chettoy** [comment]
Can you leave your e-mail address?

**Comment by deximy** [comment]
> Can you leave your e-mail address?

deximy@gmail.com

**Comment by 1956803010** [comment]
为啥这三个，我放在了同一文件夹，发生闪退，大佬救命

**Comment by deximy** [comment]
> 为啥这三个，我放在了同一文件夹，发生闪退，大佬救命

新开一个issue，详细描述程序何时退出、退出时输出内容。

**Comment by Liberal66** [comment]
大佬你好，我的在使用过程中提示 完成考试时出错，错误代码： {'code': 4823, 'msg': 'Verification code failed.', 'status_code': 200}
我试了几次都是这个问题，请问如何解决？谢谢

**Comment by chettoy** [comment]
> 大佬你好，我的在使用过程中提示 完成考试时出错，错误代码： {'code': 4823, 'msg': 'Verification code failed.', 'status_code': 200}
> 我试了几次都是这个问题，请问如何解决？谢谢

应该新开一个issue，这个issue主题是讨论怎么存储题库的。
你遇到的问题，我觉得你用的不是最新版1.3。你可以打开cmd，把程序拖进去，显示xx.exe，输入【空格】-v回车来查看版本

**Comment by Liberal66** [comment]
> > 大佬你好，我的在使用过程中提示 完成考试时出错，错误代码： {'code': 4823, 'msg': 'Verification code failed.', 'status_code': 200}
> > 我试了几次都是这个问题，请问如何解决？谢谢
> 
> 应该新开一个issue，这个issue主题是讨论怎么存储题库的。
> 你遇到的问题，我觉得你用的不是最新版1.3。你可以打开cmd，把程序拖进去，显示xx.exe，输入【空格】-v回车来查看版本

刚开始接触github，很抱歉在此issue提问了。通过更新版本，我的问题已解决，再次感谢大佬。

**Comment by wang281** [comment]
![2021-02-08](https://user-images.githubusercontent.com/78578297/107168996-c6517d80-69f7-11eb-84e7-35d5fee22212.png)


滴滴 大佬我来了 ~  现在官方更新答题次数限制了么？现在显示答题次数用完等待10min.....

**Comment by wang281** [comment]
> ![2021-02-08](https://user-images.githubusercontent.com/78578297/107168996-c6517d80-69f7-11eb-84e7-35d5fee22212.png)
> 
> 滴滴 大佬我来借楼了 ~ 现在官方更新答题次数限制了么？现在显示答题次数用完等待10min.....

**Comment by chettoy** [comment]
> 
> 
> > ![2021-02-08](https://user-images.githubusercontent.com/78578297/107168996-c6517d80-69f7-11eb-84e7-35d5fee22212.png)
> > 滴滴 大佬我来借楼了 ~ 现在官方更新答题次数限制了么？现在显示答题次数用完等待10min.....

现在的答题速度是经过多次调整的，是实测不会触发次数限制的较快速度。一定时间内答题次数过多会无法答题约25分钟。一般操作没有遇到这种情况

**Comment by wang281** [comment]
等过段时间重新试了好几次还是这个毛病...

**Comment by deximy** [comment]
> 等过段时间重新试了好几次还是这个毛病...

过一天再试呢？

**Comment by wang281** [comment]
还是如此。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "deximy"<notifications@github.com&gt;; 
发送时间: 2021年2月9日(星期二) 中午12:45
收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 
抄送: "Ⱥ~"<931619886@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [deximy/FxxkSsxx] Is there any necessity to use database? (#17)





  
等过段时间重新试了好几次还是这个毛病...
  
过一天再试呢？

**Comment by deximy** [comment]
> 还是如此。。。

那网页中能正常开始考试吗？

**Comment by chettoy** [comment]
> 
> 还是如此。。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "deximy"<notifications@github.com&gt;; 发送时间: 2021年2月9日(星期二) 中午12:45 收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 抄送: "Ⱥ~"<931619886@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [deximy/FxxkSsxx] Is there any necessity to use database? (#17) 等过段时间重新试了好几次还是这个毛病... 过一天再试呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

是每次一开始就出现这种情况还是中途出现？如果是一开始就出现可能和你的账号有关，换其他人账号试试是否正常

**Comment by wang281** [comment]
一开始就这个样子，。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chettoy"<notifications@github.com&gt;; 
发送时间: 2021年2月9日(星期二) 中午1:00
收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 
抄送: "Ⱥ~"<931619886@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [deximy/FxxkSsxx] Is there any necessity to use database? (#17)





  
还是如此。。。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "deximy"<notifications@github.com&gt;; 发送时间: 2021年2月9日(星期二) 中午12:45 收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 抄送: "Ⱥ~"<931619886@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [deximy/FxxkSsxx] Is there any necessity to use database? (#17) 等过段时间重新试了好几次还是这个毛病... 过一天再试呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是每次一开始就出现这种情况还是中途出现？如果是一开始就出现可能和你的账号有关，换其他人账号试试是否正常

**Comment by deximy** [comment]
> 一开始就这个样子，。。。

网页也无法正常开始测试的话就是账号问题。

**Comment by chettoy** [comment]
> 
> 
> > 一开始就这个样子，。。。
> 
> 网页也无法正常开始测试的话就是账号问题。

没准之前用过什么刷过头被封IP了

**Comment by wang281** [comment]
网页闪 进不去。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chettoy"<notifications@github.com&gt;; 
发送时间: 2021年2月9日(星期二) 中午1:57
收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 
抄送: "Ⱥ~"<931619886@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [deximy/FxxkSsxx] Is there any necessity to use database? (#17)





   
一开始就这个样子，。。。
  
网页也无法正常开始测试的话就是账号问题。
  
没准之前用过什么刷过头被封IP了

**Comment by deximy** [comment]
> 网页闪 进不去。。。。。

网页也进不去就不是程序的问题。私聊我token，我试一下是不是IP被封了。

**Comment by chettoy** [comment]
> 
> 
> > 网页闪 进不去。。。。。
> 
> 网页也进不去就不是程序的问题。私聊我token，我试一下是不是IP被封了。

这个错误代码代表一定时间内答题次数过多，会阻止一切答题相关请求，网页也打不开答题，要试请至少等25分钟解除后再试
