### ISSUE TITLE
Keep the token automatically refreshed

### ISSUE THREAD

**Issue by deximy** [deximy/FxxkSsxx#19]
How about keeping the token automatically refreshed on? @chettoy

**Comment by chettoy** [comment]
3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.

**Comment by deximy** [comment]
> 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.

Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.

**Comment by chettoy** [comment]
> 
> 
> > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> 
> Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.

三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪

**Comment by deximy** [comment]
> > > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> > 
> > 
> > Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.
> 
> 三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪

不开的话，我怕助长那批卖程序的人的贪婪

**Comment by chettoy** [comment]
> 
> 
> > > > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> > > 
> > > 
> > > Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.
> > 
> > 
> > 三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪
> 
> 不开的话，我怕助长那批卖程序的人的贪婪

Hmm..要不加个说明，在readme里介绍一下这些选项，补充到使用方法下面，进阶
告诉大家`FxxkSsxx.exe -h`查看帮助，-v查看版本
我用的时候都直接`FxxkSsxx.exe -ai --mode=2`，我觉得这样挺优雅的
下个版本直接加服务端验证吧，在此之前不发新版

**Comment by deximy** [comment]
> > > > > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> > > > 
> > > > 
> > > > Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.
> > > 
> > > 
> > > 三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪
> > 
> > 
> > 不开的话，我怕助长那批卖程序的人的贪婪
> 
> Hmm..要不加个说明，在readme里介绍一下这些选项，补充到使用方法下面，进阶
> 告诉大家`FxxkSsxx.exe -h`查看帮助，-v查看版本
> 我用的时候都直接`FxxkSsxx.exe -ai --mode=2`，我觉得这样挺优雅的
> 下个版本直接加服务端验证吧，在此之前不发新版

服务端验证对开源程序没什么意义吧？

**Comment by chettoy** [comment]
> 
> 
> > > > > > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> > > > > 
> > > > > 
> > > > > Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.
> > > > 
> > > > 
> > > > 三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪
> > > 
> > > 
> > > 不开的话，我怕助长那批卖程序的人的贪婪
> > 
> > 
> > Hmm..要不加个说明，在readme里介绍一下这些选项，补充到使用方法下面，进阶
> > 告诉大家`FxxkSsxx.exe -h`查看帮助，-v查看版本
> > 我用的时候都直接`FxxkSsxx.exe -ai --mode=2`，我觉得这样挺优雅的
> > 下个版本直接加服务端验证吧，在此之前不发新版
> 
> 服务端验证对开源程序没什么意义吧？

有意义。他们用python写这样的脚本都写不出，后端用C++或java来写，不用指望他们能看懂。而且后端只是一个简单的Restful API，这个可以不开源

**Comment by deximy** [comment]
> > > > > > > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> > > > > > 
> > > > > > 
> > > > > > Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.
> > > > > 
> > > > > 
> > > > > 三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪
> > > > 
> > > > 
> > > > 不开的话，我怕助长那批卖程序的人的贪婪
> > > 
> > > 
> > > Hmm..要不加个说明，在readme里介绍一下这些选项，补充到使用方法下面，进阶
> > > 告诉大家`FxxkSsxx.exe -h`查看帮助，-v查看版本
> > > 我用的时候都直接`FxxkSsxx.exe -ai --mode=2`，我觉得这样挺优雅的
> > > 下个版本直接加服务端验证吧，在此之前不发新版
> > 
> > 
> > 服务端验证对开源程序没什么意义吧？
> 
> 有意义。他们用python写这样的脚本都写不出，后端用C++或java来写，不用指望他们能看懂。而且后端只是一个简单的Restful API，这个可以不开源

u1s1，后端我喜欢C#（

**Comment by chettoy** [comment]
> 
> 
> > > > > > > > 3 hours is sufficient for general needs. Automatic token update can be turned on through the -a or --auto parameter, which is also a consideration for raising the threshold to prevent abuse.
> > > > > > > 
> > > > > > > 
> > > > > > > Just adding one parameter can hardly prevent program from being abused. I think it's better to enable the option by default.
> > > > > > 
> > > > > > 
> > > > > > 三小时足以产生上万分，一般学校只要求几百分，正常使用不会对这个功能有需求。不默认启用作为一种门槛，如果一个人不满足每三小时可以获得上万分，又不愿意花两分钟时间了解一下命令行参数，这项功能不适合他们使用；而对于懂的或有心的人并不会造成不便。项目是为了帮助大家，不能助长贪婪
> > > > > 
> > > > > 
> > > > > 不开的话，我怕助长那批卖程序的人的贪婪
> > > > 
> > > > 
> > > > Hmm..要不加个说明，在readme里介绍一下这些选项，补充到使用方法下面，进阶
> > > > 告诉大家`FxxkSsxx.exe -h`查看帮助，-v查看版本
> > > > 我用的时候都直接`FxxkSsxx.exe -ai --mode=2`，我觉得这样挺优雅的
> > > > 下个版本直接加服务端验证吧，在此之前不发新版
> > > 
> > > 
> > > 服务端验证对开源程序没什么意义吧？
> > 
> > 
> > 有意义。他们用python写这样的脚本都写不出，后端用C++或java来写，不用指望他们能看懂。而且后端只是一个简单的Restful API，这个可以不开源
> 
> u1s1，后端我喜欢C#（逃
> 
> 但这个程序已经开源了，改成联网版本我在担心会不会有其他影响。

要改也只是把关键的验证部分放在服务端，对于原来的程序来说只是使用了外部api处理一个关键部分，影响最小。不过官方可能不会再采取对抗措施，1.3太稳定了，旧版不失效，加服务端验证就没用。我1.3发的有点着急了

**Comment by deximy** [comment]
如果之后还需要有大更新的话就可以把#17一起放到服务端，现在没什么确实更新的必要了。
