### ISSUE TITLE
有的题目没有C选项，会报错

### ISSUE THREAD

**Issue by DarkEyeR** [deximy/FxxkSsxx#23]
有的题目没有C选项，xjb蒙的时候会报越界，建议改成默认A选项

**Comment by chettoy** [comment]
其实原本是A。。。我的锅
不过我还真没遇到过没有C的题，倒是有一道信息不存在的题

**Comment by chettoy** [comment]
能提供一下错误的详细信息吗

**Comment by chettoy** [comment]
目前没有哪道题只有两个选项，由于没有更多信息，猜测可能是偶然遇到题目信息不存在的情况，最新的代码中已加入对此情况的处理，将在下个版本一并发布。issue可以关了

**Comment by deximy** [comment]
> 其实原本是A。。。我的锅
> 不过我还真没遇到过没有C的题，倒是有一道信息不存在的题

![image](https://user-images.githubusercontent.com/30504323/108612999-652e9e80-7428-11eb-99a8-6d9fa0c61993.png)
