### ISSUE TITLE
由于连接方在一段时间之后没有正确答复，，，

### ISSUE THREAD

**Issue by AAA-obj** [deximy/FxxkSsxx#24]
大佬这是怎么回事，token用一个小时左右后就这样了，
![$10GEL8 }0UZ92QCYH}BAOS](https://user-images.githubusercontent.com/77483114/107880519-283f4500-6f1a-11eb-8aa5-edefa84b5fa2.png)

**Comment by AAA-obj** [comment]
这是电脑问题还是网络问题？

**Comment by deximy** [comment]
我觉得是网络问题，访问超时了。

**Comment by chettoy** [comment]
是网络问题，检查网络后重开
