### ISSUE TITLE
> 想问下各位大佬，我输了token后闪退是怎么回事，检查了也在同一个文件，token也没有错误，但是一直闪退，且已经好几天了。求助各位大佬。

### ISSUE THREAD

**Issue by jessie-wang118** [deximy/FxxkSsxx#25]
> 想问下各位大佬，我输了token后闪退是怎么回事，检查了也在同一个文件，token也没有错误，但是一直闪退，且已经好几天了。求助各位大佬。

请提供详细信息

_Originally posted by @chettoy in https://github.com/deximy/FxxkSsxx/issues/22#issuecomment-779563593_

**Comment by jessie-wang118** [comment]
打开软件粘贴token后，.exe闪退，也无法看到如何错误，不知道为何，也不知道怎么解决，请大佬帮忙解答

**Comment by chettoy** [comment]
你是按什么键粘贴的，闪退前看到token粘贴上去了吗

**Comment by jessie-wang118** [comment]
Ctrl+v    粘贴后按了回车  页面就没了就

**Comment by chettoy** [comment]
> Ctrl+v 粘贴后按了回车 页面就没了就
是因为token不正确，解析时出错导致闪退。你确定把双引号内完整的token都复制过来了吗，可以带着双引号一起复制粘贴进去试试，保证token完整

**Comment by jessie-wang118** [comment]
都复制了，而且带着双引号复制也试过，都是闪退

**Comment by deximy** [comment]
私聊我联系方式

**Comment by hcdwq322** [comment]
你好！我也是这种情况 求解决方法

**Comment by jessie-wang118** [comment]
q   2278031195

**Comment by deximy** [comment]
Win7下粘贴不是Ctrl+V。
