### ISSUE TITLE
Excuse me

### ISSUE THREAD

**Issue by 52795** [deximy/FxxkSsxx#28]
Hello developer, do you have the idea of developing team mode of automatic learning

**Comment by deximy** [comment]
Sorry but I don't even know what the team mode is.

**Comment by 52795** [comment]
![Uploading %47O80MFJPH9NFDT_]96SAQ.png…]()

**Comment by 52795** [comment]
[https://s3.ax1x.com/2021/02/24/yLLPbD.png](url)

**Comment by deximy** [comment]
Got it. So how to set it up? What's the meaning of it?

**Comment by 52795** [comment]
[1.txt](https://github.com/deximy/FxxkSsxx/files/6035972/1.txt)
Thank you for your reply
Some users join the team, they have to earn points for the team.
Here's a "tampermonkey" program,Line 64 presents the team model.

**Comment by deximy** [comment]
Can you provide an account which has already joined a team for test?

**Comment by 52795** [comment]
emmm......I'm really sorry that I haven't joined the team yet.

**Comment by deximy** [comment]
Neither have I, so let's wait for an available account :P

**Comment by xiaoxushixin** [comment]
我已经加入团队了想求一个可以刷团队的本本

**Comment by xiaoxushixin** [comment]
I have joined the team and want to ask for a notebook that can brush the team

**Comment by deximy** [comment]
> I have joined the team and want to ask for a notebook that can brush the team

Give me your token and I will have a try.

**Comment by xiaoxushixin** [comment]
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTQ0OTkwMTYsImlhdCI6MTYxNDQ4ODIxNiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNDQ4ODIxNiwidWlkIjoiNjAyMjYzYmQzNDA1ZjRmMGIyMDQ3ZTVmIiwibmFtZSI6Ilx1OGJiOFx1NGUxNlx1NjViMCIsImNvZGUiOiI2MDIyNjNiZDM0MDVmNGYwYjIwNDdlNWYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.v5R6d0AXGkB-fffLVgoDWypEc38c2ik_zbRuAhtUBDE

**Comment by deximy** [comment]
> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTQ0OTkwMTYsImlhdCI6MTYxNDQ4ODIxNiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNDQ4ODIxNiwidWlkIjoiNjAyMjYzYmQzNDA1ZjRmMGIyMDQ3ZTVmIiwibmFtZSI6Ilx1OGJiOFx1NGUxNlx1NjViMCIsImNvZGUiOiI2MDIyNjNiZDM0MDVmNGYwYjIwNDdlNWYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.v5R6d0AXGkB-fffLVgoDWypEc38c2ik_zbRuAhtUBDE

token已过期。留一个联系方式？

**Comment by xiaoxushixin** [comment]
wechat 17852978605
qq 2436650815&nbsp;
TEL 17852978605




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "deximy"<notifications@github.com&gt;; 
发送时间: 2021年3月1日(星期一) 上午9:07
收件人: "deximy/FxxkSsxx"<FxxkSsxx@noreply.github.com&gt;; 
抄送: "二蛋"<2436650815@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [deximy/FxxkSsxx] Excuse me (#28)





  
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MTQ0OTkwMTYsImlhdCI6MTYxNDQ4ODIxNiwiaXNzIjoiSEVQRTM6QVVUSCIsIm5iZiI6MTYxNDQ4ODIxNiwidWlkIjoiNjAyMjYzYmQzNDA1ZjRmMGIyMDQ3ZTVmIiwibmFtZSI6Ilx1OGJiOFx1NGUxNlx1NjViMCIsImNvZGUiOiI2MDIyNjNiZDM0MDVmNGYwYjIwNDdlNWYiLCJpc19wZXJmZWN0Ijp0cnVlfQ.v5R6d0AXGkB-fffLVgoDWypEc38c2ik_zbRuAhtUBDE
  
token已过期。留一个联系方式？

**Comment by xiaoxushixin** [comment]
thanks

**Comment by xiaoxushixin** [comment]
wechat
17852978605
qq
2436650815

**Comment by deximy** [comment]
Should be closed by 61400fadda089391ac79076b208e9db6a7a30e08
