### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by 15936982275** [deximy/FxxkSsxx#32]
输入完整的token直接闪退了怎么处理

**Comment by deximy** [comment]
输入信息后截个图发上来

**Comment by FeanlyVer** [comment]
> 输入完整的token直接闪退了怎么怎么处理

应该是没有下载answer.txt

**Comment by 15936982275** [comment]
> 
> 
> 输入信息后截个图发上来

我下载了这个就好了answer.txt打扰了
