### ISSUE TITLE
{'status_code': 405, 'code': None, 'message': None}

### ISSUE THREAD

**Issue by 966-cell** [deximy/FxxkSsxx#5]
The following tips are also given in the webpage:

Uncaught Error: Attempting to use a disconnected port object

**Comment by 966-cell** [comment]
完成考试时出错，错误代码： {'status_code': 405, 'code': None, 'message': None}

**Comment by deximy** [comment]
出现这个之后程序退出了？

**Comment by 966-cell** [comment]
> 出现这个之后程序退出了？

没有退出，一直循环重复这一条错误提示。
28号正常运行（大概是如下）：
     开始答题 
     第x道题开始答题
     已答第x道题
     下一道题
     最后，已答x道题，答题完毕
29号尽早开始出错（大致流程如下）：
     开始答题
     第x道题开始答题（跳过已答哪道题）
     下一道题
     完成考试时出错，错误代码： {'status_code': 405, 'code': None, 'message': None}###一直循环，且无答题完毕提示

**Comment by 966-cell** [comment]
> 出现这个之后程序退出了？

您那边今天运行正常吗？

**Comment by Aiden-lucus** [comment]
exe程序运行出错，错误代码： {'status_code': 405, 'code': None, 'message': None}，请大神检查一下问题所在，谢谢

**Comment by Promiss** [comment]
都是这样的问题......

**Comment by cxtdevil** [comment]
> 该网页还提供了以下提示：
> 
> 未捕获的错误：尝试使用断开连接的端口对象

网络协议变了，把http改为https就可以了！

**Comment by Promiss** [comment]
py 格式文件内的 都改成https 都不好使

**Comment by fengsidu** [comment]
作者好  我也出现了这个问题，不清楚是什么原因。
完成考试时出错，错误代码： {'status_code': 405, 'code': None, 'message': None}

**Comment by cxtdevil** [comment]
> py格式文件内的都改成https都不好使

[复兴篇.txt](https://github.com/deximy/FxxkSsxx/files/5892072/default.txt)
你改后缀用我这个试试，我都刷半天了

**Comment by Promiss** [comment]
> > py [https]
> 
> [[.txt]](https://github.com/deximy/FxxkSsxx/files/5892072/default.txt)
一样.....
完成考试时出错，错误代码： {'status_code': 405, 'code': None, 'message': None}

**Comment by deximy** [comment]
应该已经修复了。

**Comment by Aiden-lucus** [comment]
> 应该已经修复了。

python程序可以运行成功，exe程序运行过快，依然报错

**Comment by deximy** [comment]
已经更新了Release

NiKi_Lowkey <notifications@github.com> 于2021年1月29日周五 下午4:43写道：

**Comment by 966-cell** [comment]
> 应该已经修复了。

大佬辛苦了，感谢大佬
