### ISSUE TITLE
大佬您好，我对python做自动答题脚本比较感兴趣，请问有没有什么推荐的教程可以看看，以及有什么练手项目可以做，十分感谢。

### ISSUE THREAD

**Issue by fengsidu** [deximy/FxxkSsxx#9]

**Comment by deximy** [comment]
我个人是写C++起步，Python的requests库大概看了十几分钟左右就会用了，没看过什么教程，也不是很推荐去看那些有的没的教程，浪费时间。

说白了我没觉得爬虫是什么很复杂的东西，首先先请求某个接口获取某个信息，然后再请求另一个接口获取另一个信息，最后再对信息进行处理，诸如此类。爬虫是编程思维的体现，Python的简单是因为它封装了大量的操作，但是编程思维是语言无关的，不会因为你选择了Python就会更简单。编程没有捷径。

我也不觉得有什么练手项目的必要性，如果你真的喜欢，直接开始做你想做的东西就好了。举个最简单的例子，你可以尝试着看懂这个项目的代码，至少HTTP相关的部分（答案匹配那块就别看了，写那个的时候我懒得动脑子了，那段代码我现在自己都不想看）不难理解。如果有不理解的地方就去百度或者谷歌搜索，实在无法自己解决的话也可以寻求社区帮助，或者直接来问我也行。然后用自己已经学会了的部分尝试去完成自己想干的事情，比如爬个B站视频之类。很大概率你会遇到之前没遇到的麻烦，咬着牙一点点克服、一点点研究，三五个项目做下来你就会发现其实爬虫没有你想的那么难。

祝你好运。

**Comment by fengsidu** [comment]
谢谢，真诚的谢谢您，为了我一个毫不相干的人讲了那么多东西。十分感谢。祝好！
